export const devices = [
  { name: "device1" },
  { name: "device2" },
  { name: "device3" },
  { name: "device4" },
  { name: "device5" },
  { name: "device6" },
  { name: "device7" },
  { name: "device8" },
  { name: "device9" },
  { name: "device1" },
  { name: "device12" },
  { name: "device13" },
  { name: "device14" },
  { name: "device15" },
  { name: "device16" },
  { name: "device17" },
  { name: "device18" },
  { name: "device10" },
  { name: "device1" },
  { name: "device1" },
];
