export const devices = [
  { name: "device1", index: 1 },
  { name: "device2", index: 2 },
  { name: "device3", index: 3 },
  { name: "device4", index: 4 },
  { name: "device5", index: 5 },
  { name: "device6", index: 6 },
  { name: "device7", index: 7 },
  { name: "device8", index: 8 },
  { name: "device9", index: 9 },
  { name: "device10", index: 10 },
  { name: "device12", index: 11 },
  { name: "device13", index: 12 },
  { name: "device14", index: 13 },
  { name: "device15", index: 14 },
  { name: "device16", index: 15 },
  { name: "device17", index: 16 },
  { name: "device18", index: 17 },
  { name: "device11", index: 18 },
  { name: "device20", index: 19 },
  { name: "device21", index: 20 },
];
